name: CowIRC

on:
 push:
    branches: 
        - main
        
 schedule:
    - cron: "* * */3 * *"

jobs:
  build:

    runs-on: ubuntu-latest
strategy:
      matrix:
        node-version: [10.x]
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i irc
      - run: node index.js
